baseurl: /kathmandu
title: Kathmandu Interim report
# subtitle: Content-centric blogging
author: Kathmandu Living Labs
simple_search: http://google.com/search
# description: A Jekyll theme for content-rich sites
name: tufte
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: /articles/:short_year/:title
timezone: America/New_York
destination: ./docs
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'UploadToGithub.Rakefile', 'README.md']
post:
  template: _post.txt
  extension: md
collections:
  stories:
    output: true
  dives:
    output: true
  analyses:
    output: true
page:
  template: _page.txt
  extension: md
editor: gvim
git:
  branch: master
transfer:
  command: rsync
  settings: -av
  source: _site/
  destination: ~/Git/clayh53.github.com/
